name: Deploy
on:
  pull_request:
    types:
      - closed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: use node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
